### ISSUE TITLE
Doesn't work on VueJS 2.5.17

### ISSUE THREAD

**Issue by Photoshopper** [shershen08/emoji-vue#2]
I get an error in Vue 2.5.17. Should emoji-vue work on this version?

```
[Vue warn]: Error in nextTick: "TypeError: this.emojiPopup.appendUnicodeAsImageToElement is not a function"
TypeError: this.emojiPopup.appendUnicodeAsImageToElement is not a function
    at new EmojiArea_WYSIWYG (emoji.js:349)
    at HTMLTextAreaElement.<anonymous> (emoji.js:58)
    at Function.each (backend.js:5359)
    at jQuery.fn.init.each (backend.js:5194)
    at jQuery.fn.init.$.fn.emojiarea (emoji.js:53)
    at EmojiPicker.discover (backend.js:102604)
    at VueComponent.initEmojiPlugin (backend.js:57255)
    at backend.js:57269
    at Array.<anonymous> (backend.js:17552)
    at flushCallbacks (backend.js:17473)
```

**Comment by shershen08** [comment]
@Photoshopper  I've checked it just now on a new vue project with v 2.5.17
I didn't have this error.

Can you share your setup? 
Would be great it that could be reproduce online via https://codepen.io for example.

**Comment by Photoshopper** [comment]
I'm so sorry that I bothered you. Everything works fine. The problem was that I forgot to delete old Jquery Emoji script included on a page
